version: '2.4'
services:

  # --------------------------------------------------
  # Front Proxy
  # --------------------------------------------------
  envoy-front:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./front-envoy.tmpl:/etc/envoy.tmpl
    environment:
      - SERVICE_NODE=front-proxy
      - SERVICE_CLUSTER=front-proxy
      - DISCOVERY_URL=${DISCOVERY_URL}
    expose:
      - 80
      - 10000
    ports:
      - 8000:80
      - 10000:10000
    networks:
      envoymesh: {}
      frontpod:
        aliases:
          - local-proxy


  envoy-front-statsd-exporter:
    image: prom/statsd-exporter:v0.6.0
    volumes:
      - ./statsd/statsd_exporter.yml:/tmp/statsd_mapping.conf
    command: ["-statsd.mapping-config=/tmp/statsd_mapping.conf"]
    expose:
      - 9102
      - 9125
      - 9125/udp
    networks:
      envoymesh: {}
      frontpod:
        aliases:
          - statsd


  # --------------------------------------------------
  # Service 1
  # --------------------------------------------------
  envoy-service1:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./service1-envoy.tmpl:/etc/envoy.tmpl
    environment:
      - SERVICE_NODE=service1-proxy
      - SERVICE_CLUSTER=service1
      - DISCOVERY_URL=${DISCOVERY_URL}
    expose:
      - 80
    networks:
      envoymesh: {}
      servicepod1:
        aliases:
          - local-proxy

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    environment:
      - SERVICE_NAME=1
    networks:
      servicepod1:
        aliases:
          - local-service

  registrator1:
    image: javajefe/lyft-discovery-registrator
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=envoy-service1
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service1
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}

  envoy-service1-statsd-exporter:
    image: prom/statsd-exporter:v0.6.0
    volumes:
      - ./statsd/statsd_exporter.yml:/tmp/statsd_mapping.conf
    command: ["-statsd.mapping-config=/tmp/statsd_mapping.conf"]
    expose:
      - 9102
      - 9125
      - 9125/udp
    networks:
      envoymesh: {}
      servicepod1:
        aliases:
          - statsd


  # --------------------------------------------------
  # Service 2 (first node)
  # --------------------------------------------------
  envoy-service2:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./service2-envoy.tmpl:/etc/envoy.tmpl
    environment:
      - SERVICE_NODE=service2-proxy
      - SERVICE_CLUSTER=service2
      - DISCOVERY_URL=${DISCOVERY_URL}
    expose:
      - "80"
    networks:
      envoymesh: {}
      servicepod2:
        aliases:
          - local-proxy

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    environment:
      - SERVICE_NAME=2
    networks:
      servicepod2:
        aliases:
          - local-service

  registrator2:
    image: javajefe/lyft-discovery-registrator
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=envoy-service2
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service2
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}

  envoy-service2-statsd-exporter:
    image: prom/statsd-exporter:v0.6.0
    volumes:
      - ./statsd/statsd_exporter.yml:/tmp/statsd_mapping.conf
    command: ["-statsd.mapping-config=/tmp/statsd_mapping.conf"]
    expose:
      - 9102
      - 9125
      - 9125/udp
    networks:
      envoymesh: {}
      servicepod2:
        aliases:
          - statsd


  # --------------------------------------------------
  # Service 2 (second node)
  # --------------------------------------------------
  envoy-service2a:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./service2-envoy.tmpl:/etc/envoy.tmpl
    environment:
      - SERVICE_NODE=service2a-proxy
      - SERVICE_CLUSTER=service2
      - DISCOVERY_URL=${DISCOVERY_URL}
    expose:
      - "80"
    networks:
      envoymesh: {}
      servicepod2a:
        aliases:
          - local-proxy

  service2a:
    build:
      context: .
      dockerfile: Dockerfile-service
    environment:
      - SERVICE_NAME=2a
    networks:
      servicepod2a:
        aliases:
          - local-service

  registrator2a:
    image: javajefe/lyft-discovery-registrator
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=envoy-service2a
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service2
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}

  envoy-service2a-statsd-exporter:
    image: prom/statsd-exporter:v0.6.0
    volumes:
      - ./statsd/statsd_exporter.yml:/tmp/statsd_mapping.conf
    command: ["-statsd.mapping-config=/tmp/statsd_mapping.conf"]
    expose:
      - 9102
      - 9125
      - 9125/udp
    networks:
      envoymesh: {}
      servicepod2a:
        aliases:
          - statsd


  # --------------------------------------------------
  # Lyft Service Discovery
  # --------------------------------------------------
  discovery:
    image: javajefe/lyft-discovery
    environment:
      - BACKEND_STORAGE=InMemory
      - APPLICATION_ENV=production
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      envoymesh: {}


  # --------------------------------------------------
  # Tracing (Jaeger + ElasticSearch)
  # --------------------------------------------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      tracing: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      tracing: {}

  registrator-jaeger:
    image: javajefe/lyft-discovery-registrator
    depends_on:
      - jaeger-collector
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=jaeger-collector
      - PROXY_HOST_PORT=9411
      - SERVICE_NAME=jaeger
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["/go/bin/collector-linux", "--es.server-urls=http://elasticsearch:9200", "--es.num-shards=1", "--span-storage.type=elasticsearch", "--log-level=info"]
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "14269"
      - "14268"
      - "14267"
      - "9411"
    networks:
      envoymesh: {}
      tracing: {}

  jaeger-dependencies:
    image: jaegertracing/spark-dependencies
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - STORAGE=elasticsearch
      - ES_NODES=http://elasticsearch:9200
      - ES_USERNAME=
      - ES_PASSWORD=
    networks:
      tracing: {}

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["/go/bin/query-linux", "--es.server-urls=http://elasticsearch:9200", "--span-storage.type=elasticsearch", "--log-level=debug", "--query.static-files=/go/jaeger-ui/"]
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    expose:
      - "16686"
      - "16687"
    ports:
      - "16686:16686"
    networks:
      tracing: {}


  # --------------------------------------------------
  # Monitoring (Prometheus)
  # --------------------------------------------------

  prometheus:
    image: prom/prometheus:v2.3.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - envoymesh
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:4.6.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - envoymesh
    labels:
      org.label-schema.group: "monitoring"

  # --------------------------------------------------
  # Docker infrastructure
  # --------------------------------------------------

networks:
  envoymesh: {}
  frontpod: {}
  servicepod1: {}
  servicepod2: {}
  servicepod2a: {}
  tracing: {}

volumes:
  esdata: {}
  prometheus_data: {}
  grafana_data: {}
