version: '2'
services:

  # Front Proxy
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    networks:
      envoymesh: {}

  # Service group 1
  local-envoy1:
    build:
      context: .
      dockerfile: Dockerfile-localenvoy
    volumes:
      - ./service1-envoy.yaml:/etc/service-envoy.yaml
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
    networks:
      envoymesh: {}
      servicepod1:
        aliases:
          - local-proxy

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    depends_on:
      - local-envoy1
    environment:
      - SERVICE_NAME=1
    networks:
      servicepod1:
        aliases:
          - local-service

  # Registrator for Service Discovery
  registrator1:
    image: javajefe/lyft-discovery-registrator
    depends_on:
      - local-envoy1
      - service1
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=local-envoy1
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service1
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}


  # Service group 2
  local-envoy2:
    build:
      context: .
      dockerfile: Dockerfile-localenvoy
    volumes:
      - ./service2-envoy.yaml:/etc/service-envoy.yaml
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
    networks:
      envoymesh: {}
      servicepod2:
        aliases:
          - local-proxy

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    environment:
      - SERVICE_NAME=2
    networks:
      servicepod2:
        aliases:
          - local-service

  # Registrator for Service Discovery
  registrator2:
    image: javajefe/lyft-discovery-registrator
    depends_on:
      - local-envoy2
      - service2
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=local-envoy2
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service2
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}


  local-envoy2a:
    build:
      context: .
      dockerfile: Dockerfile-localenvoy
    volumes:
      - ./service2-envoy.yaml:/etc/service-envoy.yaml
    environment:
      - SERVICE_NAME=2a
    expose:
      - "80"
    networks:
      envoymesh: {}
      servicepod2a:
        aliases:
          - local-proxy

  service2a:
    build:
      context: .
      dockerfile: Dockerfile-service
    environment:
      - SERVICE_NAME=2a
    networks:
      servicepod2a:
        aliases:
          - local-service

  # Registrator for Service Discovery
  registrator2a:
    image: javajefe/lyft-discovery-registrator
    depends_on:
      - local-envoy2a
      - service2a
    environment:
      - ENVIRONMENT=DOCKER
      - DISCOVERY_URL=${DISCOVERY_URL}
      - PROXY_NETWORK_ALIAS=local-envoy2a
      - PROXY_HOST_PORT=80
      - SERVICE_NAME=service2
      - REFRESH_INTERVAL=5
    networks:
      envoymesh: {}


  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"
    networks:
      envoymesh: {}

  # Lyft Service Discovery
  discovery:
    image: javajefe/lyft-discovery
    environment:
      - BACKEND_STORAGE=InMemory
      - APPLICATION_ENV=production
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      envoymesh: {}

networks:
  envoymesh: {}
  servicepod1: {}
  servicepod2: {}
  servicepod2a: {}

